FROM node:23.11.0-slim AS build

ENV TZ=Asia/Tokyo

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:23.11.0-slim AS production

ENV TZ=Asia/Tokyo
ENV NODE_ENV=production

WORKDIR /app

COPY --from=build /app/package*.json ./
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/next.config.ts ./

RUN npm install --omit=dev

CMD ["npm", "run", "start"] 