services:
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile.prod
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production
  bff:
    build:
      context: ./services/bff
      dockerfile: docker/Dockerfile.prod
    restart: always
    ports:
      - 3001:3001
    env_file:
      - ./services/bff/.env
    environment:
      - NODE_ENV=production
  personal:
    build:
      context: ./services/personal
      dockerfile: docker/go/Dockerfile.prod
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./services/personal/.env
    environment:
      - GO_ENV=production 